name: Vercel PR
on:
  pull_request:
    branches: [master]
    types: [opened]
jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: 'Comment PR'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            const { GITHUB_REF_NAME } = process.env;
            const deploymentUrl = `https://web-git-${GITHUB_REF_NAME}-ceskodigital.vercel.app`;
            github.issues.createComment({ issue_number, owner, repo, body: `PR se nasadí sem: ${deploymentUrl}` });
